### ISSUE TITLE
Audio player displays black box on initial page load

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/ucsc-library-digital-collections#80] opened 2018-09-27 19:06 UTC
The AV player for the Holmes and Hitchcock works displays and opaque, black box when first loading the main work page and the individual child work pages.  I can send screenshots if you need them.  If the user reloads the page, the player displays properly.

Jess thinks this was a javascript issue that happened before.

**Comment by NedHenry** [comment] 2019-05-14 18:35
I noticed something important about this bug that I want to record here. The first time we load an AV player in a browser window, it loads successfully. After that, this browser window will fail to load all other AV players (even on different pages) until it is refreshed. If you open a lecture or course in a new tab, it will load successfully. 
Given this observation, the cause of this is almost certainly the same as issue #57. The browser window is keeping our players loaded in the background, when you navigate away, and so players from different pages are interfering with one another.
I'm going to merge the two issues.

**Comment by NedHenry** [comment] 2019-10-04 18:40
This was fixed in May a few days after my last comment. I apologize for not closing the issue earlier. The following commits are relevant to the fix:
4f131c441b40a69c6a7ab227aa5b4c4753bb6022
fd7a14662a45696821de95dfa03f52d93726723c
714f09392695b62bf8236f9c102e6a06891bc42e

**Closed by NedHenry** 2019-10-04 18:40 UTC
Labels: high priority
